# Generated by Django 5.2.15 on 2026-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'job'), name='unique_job_application'),
        ),
    ]
