# Generated by Django 5.2.15 on 2026-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
