# Generated by Django 5.2.15 on 2026-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_education_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
