# Generated by Django 5.2.15 on 2026-07-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_education_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='qualification_level',
        ),
    ]
