# Generated by Django 5.2.15 on 2026-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_education_remove_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(default='degree', max_length=50),
        ),
    ]
