# Generated by Django 5.2.15 on 2026-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='qualification_level',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
