# Generated by Django 5.2.15 on 2026-07-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_education_qualification_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='qualification_level',
            new_name='qualification',
        ),
    ]
