# Generated by Django 5.2.15 on 2026-07-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_qualification_level_education_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='qualification',
            new_name='qualification_level',
        ),
    ]
